apiVersion : apps/v1
kind: Deployment
metadata:
  name: lairdptestflaskcloudrun 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lairdptestflaskcloudrun
  template:
    metadata:
      labels:
        app: lairdptestflaskcloudrun 
    spec:
      containers:
        - name: lairdptestflaskcloudrun 
          image: labo5test.azurecr.io/lairdptestflaskcloudrun
          ports:
          - containerPort: 80